[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["src", "api", "chunking", "cli", "embedding", "ingestion", "retrieval", "sdk", "vectorstore"]